Repository DSM-Today/IOS, pull requests merged in 2022-11, with the labels that each got.

#53 🔀 :: (#50) Lotto Screen UI
  iOS/Sources/Presentation/Scene/LottoPage/LottoViewController.swift
Labels: 퍼블리싱

#60 🔀 :: (#58) RxFlow를 세팅합니다.
  PackageLibrary/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/SPM.swift
  iOS/Resources/LaunchScreen.storyboard
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Application/Flow/AppFlow.swift
  iOS/Sources/Application/Flow/OnboardingFlow.swift
  iOS/Sources/Application/Flow/TodayStep.swift
  iOS/Sources/Application/SceneDelegate.swift
  iOS/Sources/Presentation/Scene/Onboarding/OnboardingViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Music/MusicViewController.swift
Labels: 기능 추가

#61 🔀::(#59) 회원정보입력 페이지 퍼블리싱
  iOS/Sources/Presentation/Scene/Information/LottoPage/LottoViewController.swift
  iOS/Sources/Presentation/Scene/UserProfile/UserProfileViewController.swift
Labels: 퍼블리싱

#70 🔀 :: (#64) 카테고리 변경
  Service/Sources/Data/Remote/API/AuthAPI.swift
  Service/Sources/Data/Remote/DataSource/Information/InformationRemoteDataSourceImpl.swift
  Service/Sources/Data/Remote/DataSource/Random/RandomRemoteDataSourceImpl.swift
  Service/Sources/Data/Remote/DataSource/Suggest/SuggestRemoteDataSourceImpl.swift
  Service/Sources/Data/Remote/Response/Information/InformationSubjectListResponse.swift
  Service/Sources/Data/Remote/Response/Random/RandomSubjectListResponse.swift
  Service/Sources/Data/Remote/Response/Subject/SubjectResponse.swift
  Service/Sources/Data/Remote/Response/Suggest/SuggestSubjectListResponse.swift
  Service/Sources/Data/Remote/Response/Suggest/TodoResponse.swift
  Service/Sources/Domain/Entity/Subject/Subject.swift
  Service/Sources/Domain/Entity/Suggest/Todo.swift
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Application/Flow/AppFlow.swift
  iOS/Sources/Application/Flow/InformationFlow.swift
  iOS/Sources/Application/Flow/MainFlow.swift
  iOS/Sources/Application/Flow/RandomFlow.swift
  iOS/Sources/Application/Flow/RecommendFlow.swift
  iOS/Sources/Application/Flow/TodayStep.swift
  iOS/Sources/Extension/UINavigationBar+setBackButtonToArrow.swift
  iOS/Sources/Presentation/Scene/Category/CategoryTableViewCell.swift
  iOS/Sources/Presentation/Scene/Category/Information/InformationCategoryViewController.swift
  iOS/Sources/Presentation/Scene/Category/Information/InformationCategoryViewModel.swift
  iOS/Sources/Presentation/Scene/Category/Random/RandomCategoryViewController.swift
  iOS/Sources/Presentation/Scene/Category/Random/RandomCategoryViewModel.swift
  iOS/Sources/Presentation/Scene/Category/Recommend/RecommendCategoryViewController.swift
  iOS/Sources/Presentation/Scene/Category/Recommend/RecommendCategoryViewModel.swift
  iOS/Sources/Presentation/Scene/Information/LottoPage/LottoViewController.swift
  iOS/Sources/Presentation/Scene/Information/News/NewsViewController.swift
  iOS/Sources/Presentation/Scene/MainPage/MainToDoTableViewCell.swift
  iOS/Sources/Presentation/Scene/MainPage/MainViewController.swift
  iOS/Sources/Presentation/Scene/MainPage/MainViewModel.swift
  iOS/Sources/Presentation/Scene/Random/Character/CharacterViewController.swift
  iOS/Sources/Presentation/Scene/Random/Flower/FlowerViewController.swift
  iOS/Sources/Presentation/Scene/Random/Fortune/FortuneViewController.swift
  iOS/Sources/Presentation/Scene/Random/Idiom/IdiomViewController.swift
  iOS/Sources/Presentation/Scene/Random/Quiz/QuizViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Book/BookViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/CafeMenu/CafeMenuViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/FoodPage/FoodViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Movie/MovieViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Music/MusicViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Webtoon/WebtoonViewController.swift
Labels: 기능 추가

#74 🔀::(#66) 꽃 ViewModel
  iOS/Sources/Presentation/Scene/Random/Flower/FlowerViewController.swift
  iOS/Sources/Presentation/Scene/Random/Flower/FlowerViewModel.swift
Labels: 기능 추가

#72 🔀::(#69) 책 ViewModel 연동
  Service/Sources/Data/Remote/Response/Suggest/BookResponse.swift
  Service/Sources/Domain/Entity/Suggest/Book.swift
  iOS/Sources/Presentation/Scene/Recommend/Book/BookViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Book/BookViewModel.swift
Labels: 기능 추가

#75 🔀::(#67)사자성어 ViewModel
  iOS/Sources/Presentation/Scene/Random/Flower/FlowerViewModel.swift
  iOS/Sources/Presentation/Scene/Random/Fortune/FortuneViewController.swift
  iOS/Sources/Presentation/Scene/Random/Idiom/IdiomViewController.swift
  iOS/Sources/Presentation/Scene/Random/Idiom/IdiomViewModel.swift
Labels: 기능 추가

#77 🔀 :: (#71) TabBar 세팅하기
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Application/Flow/AppFlow.swift
  iOS/Sources/Application/Flow/AppStepper.swift
  iOS/Sources/Application/Flow/ChatFlow.swift
  iOS/Sources/Application/Flow/InformationFlow.swift
  iOS/Sources/Application/Flow/MainFlow.swift
  iOS/Sources/Application/Flow/OnboardingFlow.swift
  iOS/Sources/Application/Flow/ProfileFlow.swift
  iOS/Sources/Application/Flow/RandomFlow.swift
  iOS/Sources/Application/Flow/RecommendFlow.swift
  iOS/Sources/Application/Flow/TabsFlow.swift
  iOS/Sources/Application/Flow/TodayStep.swift
  iOS/Sources/Extension/String+toTodayStep.swift
  iOS/Sources/Presentation/Scene/Category/Information/InformationCategoryViewController.swift
  iOS/Sources/Presentation/Scene/Category/Information/InformationCategoryViewModel.swift
  iOS/Sources/Presentation/Scene/Category/Random/RandomCategoryViewController.swift
  iOS/Sources/Presentation/Scene/Category/Random/RandomCategoryViewModel.swift
  iOS/Sources/Presentation/Scene/Category/Recommend/RecommendCategoryViewController.swift
  iOS/Sources/Presentation/Scene/Category/Recommend/RecommendCategoryViewModel.swift
  iOS/Sources/Presentation/Scene/Chat/ChatViewController.swift
  iOS/Sources/Presentation/Scene/Chat/ChatViewModel.swift
  iOS/Sources/Presentation/Scene/Information/LottoPage/LottoViewController.swift
  iOS/Sources/Presentation/Scene/Information/LottoPage/LottoViewModel.swift
  iOS/Sources/Presentation/Scene/Information/News/NewsViewController.swift
  iOS/Sources/Presentation/Scene/Information/News/NewsViewModel.swift
  iOS/Sources/Presentation/Scene/MyPage/MyPageViewController.swift
  iOS/Sources/Presentation/Scene/MyPage/MyPageViewModel.swift
  iOS/Sources/Presentation/Scene/Random/Character/CharacterViewController.swift
  iOS/Sources/Presentation/Scene/Random/Character/CharacterViewModel.swift
  iOS/Sources/Presentation/Scene/Random/Flower/FlowerViewController.swift
  iOS/Sources/Presentation/Scene/Random/Fortune/FortuneViewController.swift
  iOS/Sources/Presentation/Scene/Random/Idiom/IdiomViewController.swift
  iOS/Sources/Presentation/Scene/Random/Quiz/QuizViewController.swift
  iOS/Sources/Presentation/Scene/Random/Quiz/QuizViewModel.swift
  iOS/Sources/Presentation/Scene/Recommend/Book/BookViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/CafeMenu/CafeMenuViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/CafeMenu/CafeMenuViewModel.swift
  iOS/Sources/Presentation/Scene/Recommend/FoodPage/FoodViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/FoodPage/FoodViewModel.swift
  iOS/Sources/Presentation/Scene/Recommend/Movie/MovieViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Movie/MovieViewModel.swift
  iOS/Sources/Presentation/Scene/Recommend/Music/MusicViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Music/MusicViewModel.swift
  iOS/Sources/Presentation/Scene/Recommend/Webtoon/WebtoonViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Webtoon/WebtoonViewModel.swift
Labels: 기능 추가

#80 🔀 :: (#79) 오늘의 인물
  Service/Sources/DI/RandomDependency.swift
  Service/Sources/Data/Remote/API/RandomAPI.swift
  Service/Sources/Data/Remote/DataSource/Random/RandomRemoteDataSource.swift
  Service/Sources/Data/Remote/DataSource/Random/RandomRemoteDataSourceImpl.swift
  Service/Sources/Data/Remote/Response/Random/CharacterResponse.swift
  Service/Sources/Data/Repository/RandomRepositoryImpl.swift
  Service/Sources/Domain/Entity/Random/Character.swift
  Service/Sources/Domain/Repository/RandomRepository.swift
  Service/Sources/Domain/UseCase/Random/BookmarkCharacterUseCase.swift
  Service/Sources/Domain/UseCase/Random/DeleteBookmarkCharacterUseCase.swift
  Service/Sources/Domain/UseCase/Random/FetchCharacterUseCase.swift
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Presentation/Scene/Information/LottoPage/LottoViewController.swift
  iOS/Sources/Presentation/Scene/Random/Character/CharacterViewController.swift
  iOS/Sources/Presentation/Scene/Random/Character/CharacterViewModel.swift
  iOS/Sources/Presentation/Scene/Random/Flower/FlowerViewController.swift
  iOS/Sources/Presentation/Scene/Random/Idiom/IdiomViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/CafeMenu/CafeMenuViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/FoodPage/FoodViewController.swift
Labels: 기능 추가

#82 🔀::(#78) 영화 & 책 ViewModel
  Service/Sources/Data/Remote/Response/Suggest/BookResponse.swift
  Service/Sources/Data/Remote/Response/Suggest/MovieResponse.swift
  Service/Sources/Domain/Entity/Suggest/Book.swift
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Presentation/Scene/Random/Flower/FlowerViewController.swift
  iOS/Sources/Presentation/Scene/Random/Fortune/FortuneViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Book/BookBottomSheetViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Book/BookViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Movie/MovieBottomSheetViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Movie/MovieViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Movie/MovieViewModel.swift
Labels: 기능 추가

#84 🔀 :: (#81) 퀴즈 화면 뷰모델 연동
  Service/Sources/Data/Remote/Response/Random/QuizResponse.swift
  Service/Sources/Domain/Entity/Random/Quiz.swift
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Presentation/Scene/Random/Quiz/QuizViewController.swift
  iOS/Sources/Presentation/Scene/Random/Quiz/QuizViewModel.swift
Labels: 기능 추가

#86 🔀 :: (#85) 웹툰 기능 구현
  Service/Sources/Data/Remote/Response/Suggest/WebtoonResponse.swift
  Service/Sources/Domain/Entity/Suggest/Webtoon.swift
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Presentation/Scene/Recommend/Webtoon/WebtoonViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Webtoon/WebtoonViewModel.swift
Labels: 기능 추가

#88 🔀::(#83)카페메뉴 ViewModel
  Service/Sources/Data/Remote/Response/Suggest/CafeMenuResponse.swift
  Service/Sources/Domain/Entity/Suggest/CafeMenu.swift
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Presentation/Scene/Recommend/CafeMenu/CafeMenuViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/CafeMenu/CafeMenuViewModel.swift
Labels: 기능 추가

#90 🔀 :: (#87) 태원이의 똥 치움
  Service/Sources/Data/Remote/Response/Random/IdiomResponse.swift
  iOS/Sources/Presentation/Scene/Random/Flower/FlowerViewController.swift
  iOS/Sources/Presentation/Scene/Random/Idiom/IdiomViewController.swift
Labels: 기능 추가

#91 🔀 :: (#63) Music Screen ViewModel
  Service/Sources/Data/Remote/Response/Suggest/MusicResponse.swift
  Service/Sources/Domain/Entity/Suggest/Music.swift
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Presentation/Scene/Onboarding/OnboardingViewModel.swift
  iOS/Sources/Presentation/Scene/Recommend/Music/MusicViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Music/MusicViewModel.swift
  iOS/Sources/Presentation/Scene/UserProfile/UserProfileViewModel.swift
Labels: 기능 추가

#92 🔀::(#89)뉴스 뷰모델
  Service/Sources/Data/Remote/Response/Information/NewsResponse.swift
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Presentation/Scene/Information/News/NewsViewController.swift
  iOS/Sources/Presentation/Scene/Information/News/NewsViewModel.swift
Labels: 기능 추가

#95 🔀::(#94) 로또 뷰모델
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Presentation/Scene/Information/LottoPage/LottoViewController.swift
  iOS/Sources/Presentation/Scene/Information/LottoPage/LottoViewModel.swift
Labels: 기능 추가

#96 🔀 :: (#76) FoodScreen ViewModel
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Presentation/Scene/Recommend/FoodPage/FoodViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/FoodPage/FoodViewModel.swift
Labels: 기능 추가

#98 🔀::(#97) 운세 뷰모델 해결..
  Service/Sources/Data/Remote/Response/Random/LuckyResponse.swift
  Service/Sources/Domain/Entity/Random/Lucky.swift
  iOS/Sources/Application/Flow/OnboardingFlow.swift
  iOS/Sources/Presentation/Scene/Information/LottoPage/LottoViewController.swift
  iOS/Sources/Presentation/Scene/Random/Fortune/FortuneViewController.swift
  iOS/Sources/Presentation/Scene/Random/Fortune/FortuneViewModel.swift
Labels: 기능 추가

#99 🔀 :: (#93) 프로필 기능을 구현함
  Service/Sources/DI/AuthServiceDependency.swift
  Service/Sources/DI/ImageServiceDependency.swift
  Service/Sources/DI/InformationServiceDependency.swift
  Service/Sources/DI/RandomServiceDependency.swift
  Service/Sources/DI/SuggestServiceDependency.swift
  Service/Sources/DI/UserServiceDependency.swift
  Service/Sources/Data/Remote/API/ImageAPI.swift
  Service/Sources/Data/Remote/API/TodayAPI.swift
  Service/Sources/Data/Remote/DataSource/Image/ImageRemoteDataSource.swift
  Service/Sources/Data/Remote/DataSource/Image/ImageRemoteDataSourceImpl.swift
  Service/Sources/Data/Remote/DataSource/User/UserRemoteDataSource.swift
  Service/Sources/Data/Remote/DataSource/User/UserRemoteDataSourceImpl.swift
  Service/Sources/Data/Remote/Response/Image/ImageResponse.swift
  Service/Sources/Data/Remote/Response/Subject/BookmarkSubjectResponse.swift
  Service/Sources/Data/Remote/Response/User/BookmarkListResponse.swift
  Service/Sources/Data/Remote/Response/User/ProfileResponse.swift
  Service/Sources/Data/Repository/ImageRepositoryImpl.swift
  Service/Sources/Data/Repository/UserRepositoryImpl.swift
  Service/Sources/Domain/Entity/Image/Image.swift
  Service/Sources/Domain/Entity/Subject/BookmarkSubject.swift
  Service/Sources/Domain/Repository/ImageRepository.swift
  Service/Sources/Domain/Repository/UesrRepository.swift
  Service/Sources/Domain/UseCase/Image/PostImageUseCase.swift
  Service/Sources/Domain/UseCase/User/FetchBookmarkListUseCase.swift
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Application/Flow/AppStepper.swift
  iOS/Sources/Application/Flow/ProfileFlow.swift
  iOS/Sources/Application/Flow/TodayStep.swift
  iOS/Sources/Extension/UITextField+addLeftPadding.swift
  iOS/Sources/Presentation/Scene/EditProfile/EditProfileViewController.swift
  iOS/Sources/Presentation/Scene/EditProfile/EditProfileViewModel.swift
  iOS/Sources/Presentation/Scene/MainPage/MainViewController.swift
  iOS/Sources/Presentation/Scene/MyPage/MyPageTableViewCell.swift
  iOS/Sources/Presentation/Scene/MyPage/MyPageViewController.swift
  iOS/Sources/Presentation/Scene/MyPage/MyPageViewModel.swift
  iOS/SupportingFiles/Info.plist
Labels: 기능 추가

#102 🔀::(#101) 라벨 수정
  iOS/Sources/Presentation/Scene/EditProfile/EditProfileViewController.swift
  iOS/Sources/Presentation/Scene/Information/LottoPage/LottoViewController.swift
  iOS/Sources/Presentation/Scene/Information/News/NewsViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Book/BookViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Movie/MovieViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Music/MusicViewController.swift
Labels: 자잘한 수정
