Repository DSM-Today/IOS, pull requests merged in 2022-10, with the labels that each got.

#10 🔀 :: (#9) 온보딩 화면 퍼블리싱
  iOS/Resources/Color.xcassets/Brown1.colorset/Contents.json
  iOS/Resources/Image.xcassets/Google.imageset/Contents.json
  iOS/Resources/Image.xcassets/Google.imageset/googl2.png
  iOS/Resources/Image.xcassets/Google.imageset/googl3.png
  iOS/Resources/Image.xcassets/Google.imageset/google1.png
  iOS/Resources/Image.xcassets/Kakao.imageset/Contents.json
  iOS/Resources/Image.xcassets/Kakao.imageset/kakao1.png
  iOS/Resources/Image.xcassets/Kakao.imageset/kakao2.png
  iOS/Resources/Image.xcassets/Kakao.imageset/kakao3.png
  iOS/Resources/Image.xcassets/Logo2.imageset/Contents.json
  iOS/Resources/Image.xcassets/Logo2.imageset/LogoImage1.png
  iOS/Resources/Image.xcassets/Logo2.imageset/LogoImage2.png
  iOS/Resources/Image.xcassets/Logo2.imageset/LogoImage3.png
  iOS/Resources/Image.xcassets/Naver.imageset/Contents.json
  iOS/Resources/Image.xcassets/Naver.imageset/naver1.png
  iOS/Resources/Image.xcassets/Naver.imageset/naver2.png
  iOS/Resources/Image.xcassets/Naver.imageset/naver3.png
  iOS/Sources/Application/SceneDelegate.swift
  iOS/Sources/Presentation/Scene/Onboarding/OnboardingViewController.swift
  iOS/Sources/Presentation/ViewController.swift
Labels: 퍼블리싱

#15 🔀 :: (#14) Color 추가
  iOS/Resources/Color.xcassets/Blue9.colorset/Contents.json
  iOS/Resources/Color.xcassets/Gray3.colorset/Contents.json
  iOS/Sources/Presentation/Extension/UIColor+setColor.swift
Labels: 프로젝트 세팅

#17 🔀 :: (#16) 온보딩 화면 다시 퍼블리싱
  iOS/Sources/Presentation/Scene/Onboarding/OnboardingViewController.swift
Labels: 퍼블리싱

#18 🔀 :: (#11) MainScreen UI
  iOS/Resources/Image.xcassets/Calendar.imageset/CALENDAR 1.png
  iOS/Resources/Image.xcassets/Calendar.imageset/CALENDAR 2.png
  iOS/Resources/Image.xcassets/Calendar.imageset/CALENDAR.png
  iOS/Resources/Image.xcassets/Calendar.imageset/Contents.json
  iOS/Resources/Image.xcassets/Main.imageset/Contents.json
  iOS/Resources/Image.xcassets/Main.imageset/Ellipse 600.png
  iOS/Resources/Image.xcassets/Main.imageset/Ellipse 60000.png
  iOS/Resources/Image.xcassets/Main.imageset/Ellipse 60000000.png
  iOS/Sources/Presentation/Scene/Mainpage/MainToDoTableViewCell.swift
  iOS/Sources/Presentation/Scene/Mainpage/MainViewController.swift
  iOS/Sources/Presentation/Subviews/CategoryView.swift
Labels: 퍼블리싱

#22 🔀 :: (#20) 퍼블리싱 코드 리펙토링
  iOS/Sources/Presentation/Scene/EditProfile/EditProfileViewController.swift
  iOS/Sources/Presentation/Scene/MyPage/MyPageTableViewCell.swift
  iOS/Sources/Presentation/Scene/MyPage/MyPageViewController.swift
Labels: 리펙토링

#23 🔀 :: (#21) EditProfileViewController 구현
  iOS/Sources/Presentation/Scene/EditProfile/EditProfileViewController.swift
Labels: 퍼블리싱

#26 🔀 :: (#25) 영화 화면 퍼블리싱
  iOS/Sources/Presentation/Scene/Movie/MovieBottomSheetViewController.swift
  iOS/Sources/Presentation/Scene/Movie/MovieViewController.swift
  iOS/Sources/ResourceCode/Color.swift
  iOS/Sources/ResourceCode/Font.swift
Labels: 퍼블리싱

#28 🔀 :: (#24) RecommendCafeMenu 퍼블리싱
  iOS/Sources/Presentation/Scene/EditProfile/EditProfileViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/CafeMenu/CafeMenuViewController.swift
Labels: 퍼블리싱

#30 🔀 :: (#27) 사자성어 화면 퍼블리싱
  iOS/Sources/Presentation/Scene/Idiom/IdiomViewController.swift
Labels: 퍼블리싱

#31 🔀 :: (#29) 인물 화면 퍼블리싱
  iOS/Sources/Presentation/Scene/Random/Character/CharacterViewController.swift
Labels: 퍼블리싱

#33 🔀 :: (#29) 화면 수정
  iOS/Sources/Presentation/Scene/EditProfile/EditProfileViewController.swift
  iOS/Sources/Presentation/Scene/MyPage/MyPageViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/CafeMenu/CafeMenuViewController.swift
Labels: 자잘한 수정

#35 🔀:: (#34) 운세 화면 퍼블리싱
  iOS/Sources/Presentation/Scene/Random/Fortune/FortuneViewController.swift
Labels: 퍼블리싱

#36 🔀 :: (#19) CategoryScreen UI
  iOS/Sources/Presentation/Scene/CategoryPage/CategoryTableViewCell.swift
  iOS/Sources/Presentation/Scene/CategoryPage/CategoryViewController.swift
  iOS/Sources/Presentation/Scene/MyPage/MyPageTableViewCell.swift
Labels: 퍼블리싱

#42 🔀 :: (#40) 웹툰 화면 퍼블리싱
  iOS/Sources/Presentation/Scene/Webtoon/WebtoonViewController.swift
Labels: 퍼블리싱

#45 🔀 :: (#44) 뉴스 화면 퍼블리싱
  iOS/Sources/Presentation/Scene/News/NewsViewController.swift
Labels: 퍼블리싱

#46 🔀 :: (#41) Music Screen UI
  iOS/Sources/Presentation/Scene/Movie/MovieViewController.swift
  iOS/Sources/Presentation/Scene/MusicPage/MusicPageViewController.swift
Labels: 퍼블리싱

#47 🔀:: (#39) 랜덤 퀴즈 화면 퍼블리싱
  iOS/Sources/Extension/UIViewController+Alert.swift
  iOS/Sources/Presentation/Scene/Random/Quiz/QuizViewController.swift
Labels: 퍼블리싱

#48 🔀 :: (#43) Food Screen UI
  iOS/Sources/Presentation/Scene/FoodPage/FoodViewController.swift
Labels: 퍼블리싱

#51 🔀 :: (#49) setNavigation 구현
  iOS/Sources/Extension/UIViewController+setNavigation.swift
  iOS/Sources/Presentation/Scene/Category/CategoryTableViewCell.swift
  iOS/Sources/Presentation/Scene/Category/CategoryViewController.swift
  iOS/Sources/Presentation/Scene/EditProfile/EditProfileViewController.swift
  iOS/Sources/Presentation/Scene/Information/News/NewsViewController.swift
  iOS/Sources/Presentation/Scene/MainPage/MainViewController.swift
  iOS/Sources/Presentation/Scene/MyPage/MyPageViewController.swift
  iOS/Sources/Presentation/Scene/Random/Character/CharacterViewController.swift
  iOS/Sources/Presentation/Scene/Random/Flower/FlowerViewController.swift
  iOS/Sources/Presentation/Scene/Random/Fortune/FortuneViewController.swift
  iOS/Sources/Presentation/Scene/Random/Idiom/IdiomViewController.swift
  iOS/Sources/Presentation/Scene/Random/Quiz/QuizViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/CafeMenu/CafeMenuViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/FoodPage/FoodViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Movie/MovieBottomSheetViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Movie/MovieViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Music/MusicPageViewController.swift
  iOS/Sources/Presentation/Scene/Recommend/Webtoon/WebtoonViewController.swift
Labels: 기능 추가
