Repository DSM-Today/IOS, pull requests merged in 2022-09, with the labels that each got.

#2 🔀 :: (#1) Tuist 프로젝트를 세팅합니다.
  .gitignore
  .swiftlint.yml
  Makefile
  PackageLibrary/Project.swift
  PackageLibrary/Sources/TempSource.swift
  Plugins/TodayIOS/Package.swift
  Plugins/TodayIOS/Plugin.swift
  Plugins/TodayIOS/ProjectDescriptionHelpers/LocalHelper.swift
  Plugins/TodayIOS/Sources/tuist-my-cli/main.swift
  Service/Project.swift
  Service/Sources/TempSource.swift
  Targets/TodayIOS/Resources/LaunchScreen.storyboard
  Targets/TodayIOS/Sources/AppDelegate.swift
  Targets/TodayIOS/Tests/AppTests.swift
  Targets/TodayIOSKit/Sources/TodayIOSKit.swift
  Targets/TodayIOSKit/Tests/TodayIOSKitTests.swift
  Targets/TodayIOSUI/Sources/TodayIOSUI.swift
  Targets/TodayIOSUI/Tests/TodayIOSUITests.swift
  Tuist/Config.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/OrganizationName.swift
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+excutable.swift
  Tuist/ProjectDescriptionHelpers/RemoveStaticFrameworksScripts.swift
  Tuist/ProjectDescriptionHelpers/SPM.swift
  Tuist/ProjectDescriptionHelpers/SwiftLintScript.swift
  Workspace.swift
  iOS/Project.swift
  iOS/Resources/Image.xcassets/Application.imageset/Contents.json
  iOS/Resources/Image.xcassets/Contents.json
  iOS/Resources/LaunchScreen.storyboard
  iOS/Sources/Application/AppDelegate.swift
  iOS/Sources/Application/SceneDelegate.swift
  iOS/Sources/Presentation/ViewController.swift
  iOS/SupportingFiles/Info.plist
Labels: 프로젝트 세팅

#4 🔀 :: (#3) Font Setting
  iOS/Resources/Fonts/NotoSansKR-Black.otf
  iOS/Resources/Fonts/NotoSansKR-Bold.otf
  iOS/Resources/Fonts/NotoSansKR-Light.otf
  iOS/Resources/Fonts/NotoSansKR-Medium.otf
  iOS/Resources/Fonts/NotoSansKR-Regular.otf
  iOS/Resources/Fonts/NotoSansKR-Thin.otf
  iOS/Sources/Presentation/Extension/UIFont+NotoSans.swift
  iOS/SupportingFiles/Info.plist
Labels: 프로젝트 세팅

#6 🔀 :: (#5) LaunchScreen 퍼블리싱
  iOS/Resources/Image.xcassets/Logo.imageset/Contents.json
  iOS/Resources/Image.xcassets/Logo.imageset/Today1.png
  iOS/Resources/Image.xcassets/Logo.imageset/Today2.png
  iOS/Resources/Image.xcassets/Logo.imageset/Today3.png
  iOS/Resources/LaunchScreen.storyboard
Labels: 퍼블리싱

#8 🔀 :: (#7) color setting
  iOS/Resources/Color.xcassets/Blown1.colorset/Contents.json
  iOS/Resources/Color.xcassets/Blue1.colorset/Contents.json
  iOS/Resources/Color.xcassets/Blue2.colorset/Contents.json
  iOS/Resources/Color.xcassets/Blue3.colorset/Contents.json
  iOS/Resources/Color.xcassets/Blue4.colorset/Contents.json
  iOS/Resources/Color.xcassets/Blue5.colorset/Contents.json
  iOS/Resources/Color.xcassets/Blue6.colorset/Contents.json
  iOS/Resources/Color.xcassets/Blue7.colorset/Contents.json
  iOS/Resources/Color.xcassets/Contents.json
  iOS/Resources/Color.xcassets/Gray1.colorset/Contents.json
  iOS/Resources/Color.xcassets/Gray2.colorset/Contents.json
  iOS/Resources/Color.xcassets/Green1.colorset/Contents.json
  iOS/Resources/Color.xcassets/Orange1.colorset/Contents.json
  iOS/Resources/Color.xcassets/Primary.colorset/Contents.json
  iOS/Resources/Color.xcassets/Purple1.colorset/Contents.json
  iOS/Resources/Color.xcassets/Red1.colorset/Contents.json
  iOS/Resources/Color.xcassets/Yellow1.colorset/Contents.json
  iOS/Resources/Color.xcassets/Yellow2.colorset/Contents.json
  iOS/Sources/Presentation/Extension/UIColor+setColor.swift
Labels: 기능 추가
